 <section class="section-custom-1">
        <div class="owl-carousel owl-carousel-custom" data-items="1" data-xs-items="2" data-sm-items="3" data-lg-items="4" data-xl-items="6" data-nav="true" data-dots="false" data-mouse-drag="true" data-lightgallery="group" data-stage-padding="0" data-xl-stage-padding="0">
          <div><a class="thumbnail-default thumbnail-instagram" data-lightgallery="item" href="images/portfolio/gallery-01-1200x800_original.jpg"><img src="images/portfolio/gallery-01-320x320.jpg" alt="" width="320" height="320"/><span class="icon fa-search-plus"></span></a></div>
          <div><a class="thumbnail-default thumbnail-instagram" data-lightgallery="item" href="images/portfolio/gallery-02-1200x800_original.jpg"><img src="images/portfolio/gallery-02-320x320.jpg" alt="" width="320" height="320"/><span class="icon fa-search-plus"></span></a></div>
          <div><a class="thumbnail-default thumbnail-instagram" data-lightgallery="item" href="images/portfolio/gallery-03-1200x800_original.jpg"><img src="images/portfolio/gallery-03-320x320.jpg" alt="" width="320" height="320"/><span class="icon fa-search-plus"></span></a></div>
          <div><a class="thumbnail-default thumbnail-instagram" data-lightgallery="item" href="images/portfolio/gallery-04-1200x800_original.jpg"><img src="images/portfolio/gallery-04-320x320.jpg" alt="" width="320" height="320"/><span class="icon fa-search-plus"></span></a></div>
          <div><a class="thumbnail-default thumbnail-instagram" data-lightgallery="item" href="images/portfolio/gallery-05-1200x800_original.jpg"><img src="images/portfolio/gallery-05-320x320.jpg" alt="" width="320" height="320"/><span class="icon fa-search-plus"></span></a></div>
          <div><a class="thumbnail-default thumbnail-instagram" data-lightgallery="item" href="images/portfolio/gallery-06-1200x800_original.jpg"><img src="images/portfolio/gallery-06-320x320.jpg" alt="" width="320" height="320"/><span class="icon fa-search-plus"></span></a></div>
        </div>
      </section>